version: '3.3'

volumes:
  certbot:

services:
  nginx: 
    image: nginx
    restart: unless-stopped
    container_name: nginx
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./certbot/www:/var/www/certbot/:ro"
      - "./certbot/conf/:/etc/nginx/ssl/:ro"
    networks:
      - nginx

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - "./certbot/www/:/var/www/certbot/:rw"
      - "./certbot/conf/:/etc/letsencrypt/:rw"
    command: certonly --webroot --webroot-path=/var/www/certbot/ --email [your email]  --agree-tos --no-eff-email -d [domain_name] 
    # command: certonly --webroot --webroot-path=/var/www/certbot/ --email [hamid@gmail.com]  --agree-tos --no-eff-email -d [hamid.com] 
networks:
  nginx:
    external: true  
